blog/urls.py
from django.urls import path, include
from . import views

app_name='blog'

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/', views.detail, name='detail'),

    path('test1/', views.test1),
    path('test2/<int:no>/', views.test2),
    path('test3/<year>/<month>/<day>/', views.test3),
    path('test4/', views.test4),
    path('test5/', views.test5),
    path('test6/', views.test6),
    path('tag/<id>/', views.tag_list),
    path('test7/', views.test7),
    path('new/', views.post_create, name='create'),
    path('update/<id>/', views.post_update, name='update'),
    path('delete/<id>/', views.post_delete, name='delete'),


]

gallery/urls.py
from django.urls import path
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from .models import Image

app_name = 'gallery'
urlpatterns = [
    path('', TemplateView.as_view(template_name='gallery/gallery_list.html'), name='list'),
    path('list/', ListView.as_view(model=Image), name='image_list'),
    path('detail/<pk>/', DetailView.as_view(model=Image), name='image_detail'),
    path('add/', CreateView.as_view(model=Image, fields='__all__'), name='image_add'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('book/', include('book.urls')),
    path('signlanguage/',include('signlanguage.urls')),
    path('gallery/', include('gallery.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.urls import reverse

class Image(models.Model):
    title = models.CharField(max_length=200)
    photo = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('gallery:image_list')

gallery/views.py
from django.shortcuts import render

# Create your views here.

gallery/templates/gallery/gallery_list.html
{% load static %}
<html>
  <head>  
      <link rel="stylesheet" href="{% static 'css/base.css' %}" />   
  </head>
  <body>
    <div class="wrapper">
      <img src="{% static 'images/01.jpg' %}" /> 
      <img src="{% static 'images/02.jpg' %}" /> 
      <img src="{% static 'images/03.jpg' %}" /> 
      <img src="{% static 'images/04.jpg' %}" /> 
      <img src="{% static 'images/05.jpg' %}" /> 
      <img src="{% static 'images/06.jpg' %}" /> 
      <img src="{% static 'images/07.jpg' %}" /> 
      <img src="{% static 'images/08.jpg' %}" /> 
      <img src="{% static 'images/09.jpg' %}" /> 
      <img src="{% static 'images/10.jpg' %}" /> 
    </div> 
  </body>
</html>

gallery/templates/gallery/image_detail.html
<html>
  <head></head>
  <body>
    <h1> {{image.title}} </h1>
    <img src={{image.photo.url}} />
  </body>
</html>

gallery/templates/gallery/image_form.html
<html>
   <head></head>
   <body>
      <h1>이미지 등록</h1>
      <form action="" method="post" enctype="multipart/form-data">
         {{ form.as_p }}
         {% csrf_token %}
      <p><input type="submit" value="등록"></p>
      </form>
   </body>
</html>

gallery/templates/gallery/image_list.html
<html>
  <head></head>
  <body>
    <h1> 이미지 목록 </h1>
    {% for image in image_list %}
      <li><a href="{% url 'gallery:image_detail' image.id %}">{{image}}</a></li>
    {% endfor %}
  </body>
</html>