blog/urls.py
from django.urls import path, include
from . import views

app_name='blog'

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/', views.detail, name='detail'),

    path('test1/', views.test1),
    path('test2/<int:no>/', views.test2),
    path('test3/<year>/<month>/<day>/', views.test3),
    path('test4/', views.test4),
    path('test5/', views.test5),
    path('test6/', views.test6),
    path('tag/<id>/', views.tag_list),
    path('test7/', views.test7),
    path('new/', views.post_create, name='create'),
    path('update/<id>/', views.post_update, name='update'),
    path('delete/<id>/', views.post_delete, name='delete'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('book/', include('book.urls')),
    path('signlanguage/',include('signlanguage.urls')),
    path('gallery/', include('gallery.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    REGION_CHOICE = (
                        ('Africa','아프리카'),
                        ('Europe','유럽'),
                        ('Oceania','오세아니아'),
                        ('Asia','아시아'),
                        ('North America','북아메리카'),
                        ('South America','남아메리카'),
                        )

    title = models.CharField('제목', max_length=250)
    body = models.TextField('내용')
    region = models.CharField('지역',max_length=20,choices=REGION_CHOICE, default='Asia')
    tag = models.ManyToManyField('Tag')
    ip = models.GenericIPAddressField(null=True)

    created = models.DateField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.id])



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=20)
    message = models.TextField()
    created = models.DateField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField(label='제목')
    body = forms.CharField(label='내용', widget=forms.Textarea)


from .models import Post
class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'region']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import *
from django.shortcuts import render

# Create your views here.
def test1(request):
    return HttpResponse("blog/test1 응답!")


def test2(request, no):
    print('no 타입:', type(no))
    return HttpResponse(f'no:{no}')


def test3(request, year, month, day):
    return HttpResponse(f'년:{year}, 월:{month}, 일:{day}')


# def list(request):
#     post_list = Post.objects.all()
#     titles = ''

#     for post in post_list:
#         titles += post.title

    return HttpResponse(titles)

def detail(request, id):
    post = get_object_or_404(Post, id=id)
    comment_all = post.comments.all()
    tag_list = post.tag.all()
    return render(request, 'blog/detail.html', {'post': post, 'comment_all':comment_all, 'tag_list':tag_list})



def list(request):
    post_list = Post.objects.all()    
    search_key = request.GET.get("keyword")
    if search_key:
        post_list = Post.objects.filter(title__icontains=search_key)
    return render(request, 'blog/list.html', {'post_all':post_list, 'q':search_key})

def test4(request):
    return render(request, 'blog/test4.html', {'score':70})

def test5(request):
    var ='''
    Miracles happen to only those who believe in them.
    Think like a man of action and act like man of thought.
    Courage is very important. Like a muscle, it is strengthened by use.
    Life is the art of drawing sufficient conclusions from insufficient premises.
    By doubting we come at the truth.
    A man that has no virtue in himself, ever envies virtue in others.
    When money speaks, the truth keeps silent.
    Better the last smile than the first laughter.
    '''

    return render(request, 'blog/test5.html', {'var':var})


from django.utils import timezone
def test6(request):
    d1 = timezone.now()
    d2 = timezone.datetime(2001,3,19)
    d3 = timezone.datetime(2030,3,19)

    return render(request, 'blog/test6.html', {'date1':d1, 'date2':d2, 'date3':d3})

    

def tag_list(request, id):
    tag = Tag.objects.get(id=id)
    post_list = tag.post_set.all()
    return render(request, 'blog/list.html', {'post_all':post_list})


def test7(request):
    print('요청방식 : ', request.method)
    print('GET방식으로 전달된 질의 문자열 :', request.GET)
    print('Post방식으로 전달된 질의 문자열 :', request.POST)
    print('업로드 파일 : ', request.FILES)
    return render(request, 'blog/form_test.html')

from .forms import PostForm

from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm, PostModelForm

# def post_create(request):
#     if request.method == 'POST':
#         form = PostModelForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             post = Post.objects.create(**form.cleaned_data)
#             return redirect(post)
#     else:
#         form = PostModelForm()
#         return render(request, 'blog/post_form.html', {'form':form})


# def post_create(request):
#     if request.method == 'POST':
#         form = PostModelForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             post = form.save()
#             return redirect(post)
#     else:
#         form = PostModelForm()
#         return render(request, 'blog/post_form.html', {'form':form})


def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:list')
    else:
        form = PostModelForm(instance=post)
        return render(request, 'blog/post_update.html', {'form':form})

def post_delete(request, id):
    post = Post.objects.get(id=id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:list')
    else:
        return render(request, 'blog/post_delete.html', {'post':post})


def post_create(request):
    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            return redirect(post)
    else:
        form = PostModelForm()
        return render(request, 'blog/post_form.html', {'form':form})

blog/templates/blog/detail.html
{% extends "layout.html" %}
{% block title %} Post 상세보기{% endblock %}
{% block content %}
    <h1>{{post.title}}</h1>
    제목 : {{post.title}} <br/>
    내용 : {{post.body}} <br/>
    지역 : {{post.region}} <br>
    
    <hr><p>댓글</p>
    {% for comment in comment_all %}
        <p>{{comment.message}} /{{comment.author}}/{{comment.updated}}</p>
    {% empty %}
        댓글이 존재하지 않습니다.  
    {% endfor %}

    <hr><p>태그</p>
     {% for tag in tag_list %}
        #<a href="/blog/tag/{{tag.id}}">{{tag.name}}</a>
     {% endfor %}

    <hr>
    <a href="{% url 'blog:list' %}">[목록 보기]</a>
    <a href="{% url 'blog:update' post.id %}">[글 수정]</a>
    <a href="{% url 'blog:delete' post.id %}">[글 삭제]</a>

{% endblock %}

blog/templates/blog/form_test.html
{% extends "layout.html" %}
{% block title %} Form Test {% endblock %}
{% block content %}
    <form action="" method="post"  enctype="multipart/form-data">    
        {% csrf_token %}
        아이디 : <input type="text" name="id"><br>
        비밀번호 : <input type="password" name="pwd"><br>
        사진 : <input type="file" name="image"><br>
        성별 :     
        <input type="radio" name="gender" value="male"> 남자
        <input type="radio" name="gender" value="female"> 여자 <br>
        
        관심분야:
        <input type="checkbox" name="interest" value="AI">인공지능 
        <input type="checkbox" name="interest" value="BD">빅데이터 
        <input type="checkbox" name="interest" value="DA">데이터 분석 <br>

        연령대:
        <select name="age">
            <option value="2">20대</option>
            <option value="3">30대</option>
            <option value="4">40대</option>         
        </select><br>

        참고 사항: <br>
        <textarea cols="30" rows="10" name="remark"></textarea><br>
        <input type="submit" value="확인">
    </form>
{% endblock %}

blog/templates/blog/list.html
{% extends "layout.html" %}
{% block title %} Post목록 {% endblock %}
{% block content %}
     <h1>Post 목록 보기</h1>
     <form action="" method="get">
        {% csrf_token %}
         검색어:<input type="text" name="keyword" value="{{q|default:''}}" >
         <input type="submit" value="검색">
     </form>    
 
    {% for post in post_all %}
        <a href="{% url 'blog:detail' post.id %}"> {{post.title}}</a><br>
        
    {% endfor %}
    <a href="{% url 'blog:create' %}">[새 글 쓰기]</a>

 {% endblock %}

blog/templates/blog/post_delete.html
{% extends "layout.html" %}
{% block title %}Post 삭제{% endblock %}
{% block content %}
    <h1> POST 삭제</h1>
    {{post}}  글을 정말로 삭제하시겠습니까?

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="네, 삭제합니다">
    </form>

    <a href="{% url 'blog:list'%}">아니오, 취소합니다</a>
    
{% endblock %}

blog/templates/blog/post_form.html
{% extends "layout.html" %}
{% block title %} Post 등록 {% endblock %}
{% block content %}
    <h1> POST 등록</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="등록">
    </form>
{% endblock %}

blog/templates/blog/post_update.html
{% extends "layout.html" %}

{% block title %}Post 수정{% endblock %}

{% block content %}
    <h1> POST 수정</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="수정">
    </form>
{% endblock %}

blog/templates/blog/test4.html
{% if score %}
  점수 : {{score}}
{% endif %}<br>


{% if score >= 60 %}
  합격입니다!
{% else %}
  불합격입니다.
{% endif %}<br>

{% if score >= 90 %}
   A등급
{% elif score >= 80%}
   B등급
{% else %}
   C등급
{% endif %}

blog/templates/blog/test5.html
{{var}}
<hr>
{{var|linebreaks}}
<hr>
{{var|truncatechars:100}}
<hr>
{{var|truncatewords:50}}

blog/templates/blog/test6.html
{{date1}} <br>
{{date1|date:"Y-m-d"}} <br>
{{date1|time:"P"}} <br>
{{date2|timesince}}<br>
{{date3|timeuntil}}<br>