blog/urls.py
from django.urls import path, include
from . import views

app_name='blog'

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/', views.detail, name='detail'),

    path('test1/', views.test1),
    path('test2/<int:no>/', views.test2),
    path('test3/<year>/<month>/<day>/', views.test3),
    path('test4/', views.test4),
    path('test5/', views.test5),
    path('test6/', views.test6),
    path('tag/<id>/', views.tag_list),
    path('test7/', views.test7),
    path('new/', views.post_create, name='create'),
    path('update/<id>/', views.post_update, name='update'),
    path('delete/<id>/', views.post_delete, name='delete'),


]

book/urls.py
from django.urls import path, reverse_lazy
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Book 

app_name = 'book'
urlpatterns = [
    path('', ListView.as_view(model=Book), name='list'),
    path('detail/<pk>/', DetailView.as_view(model=Book), name='detail'),
    path('create/', CreateView.as_view(model=Book, fields='__all__'), name='create'),
    path('update/<pk>/', UpdateView.as_view(model=Book, fields='__all__'), name='update'),
    path('delete/<pk>/', DeleteView.as_view(model=Book, success_url=reverse_lazy('book:list')), name='delete')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('book/', include('book.urls')),
    path('signlanguage/',include('signlanguage.urls')),
    path('gallery/', include('gallery.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.urls import reverse

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)

    def __str__(self):
        return self.title   

    def get_absolute_url(self):
        return reverse('book:list')

book/views.py
from django.shortcuts import render

# Create your views here.

book/templates/book/book_confirm_delete.html
{% extends "layout.html" %}
{% block title %}Post 삭제{% endblock %}
{% block content %}
    <h1> BOOK 삭제</h1>

    "{{book}}"을 정말로 삭제하시겠습니까?
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="네, 삭제합니다">
    </form>
    <a href="{% url 'book:list'%}">아니오, 취소합니다</a>
    
{% endblock %}

book/templates/book/book_detail.html
{% extends "layout.html" %}
{% block title %} Book 상세보기 {% endblock %}
{% block content %}
    <h1>{{book.title}}</h1>
    제목 : {{book.title}} <br>
    저자 : {{book.author}} <br>
    출판사 : {{book.publisher}} <br>
    <a href="{% url 'book:update' book.id %}">[수정하기]</a>
    <a href="{% url 'book:delete' book.id %}">[삭제하기]</a> 

{% endblock %}

book/templates/book/book_form.html
{% extends 'layout.html' %}
{% block title %}
  Book 등록
{% endblock %}
{% block content %}
  <h1>Book 등록</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="등록" />
  </form>
{% endblock %}

book/templates/book/book_list.html
{% extends "layout.html" %}
{% block title %} Book 목록 {% endblock %}
{% block content %}
    <h1>Book 목록 보기</h1>
    {% for book in book_list %}
        <a href="{% url 'book:detail' book.id %}"> {{book.title}}</a><br>
    {% endfor %}
    <a href="{% url 'book:create' %}">[새 책 등록]</a>

{% endblock %}